UCS/BITMAP/TEST: Fix build with >= Clang 21
First caught on Gentoo LLVM with Clang 21.1.5 and LLVM 21.1.5
Build with fail with the following error message

core/ucp_context.c:2673:47: error: default initialization of an object of type
      'typeof (*tl_bitmap_super)' (aka 'const ucp_tl_bitmap_t') leaves the object uninitialized
      [-Werror,-Wdefault-const-init-var-unsafe]
/var/tmp/portage/sys-cluster/ucx-1.19.0/work/ucx-1.19.0/src/ucs/datastruct/static_bitmap.h:250:5: note:
      expanded from macro 'UCS_STATIC_BITMAP_NOT'
  250 |     UCS_STATIC_BITMAP_UNARY_OP(_bitmap, not, UCS_PP_UNIQUE_ID)
      |     ^
/var/tmp/portage/sys-cluster/ucx-1.19.0/work/ucx-1.19.0/src/ucs/datastruct/static_bitmap.h:239:5: note:
      expanded from macro 'UCS_STATIC_BITMAP_UNARY_OP'
  239 |     _UCS_STATIC_BITMAP_UNARY_OP(_bitmap, _op_name, _uid)
      |     ^
/var/tmp/portage/sys-cluster/ucx-1.19.0/work/ucx-1.19.0/src/ucs/datastruct/static_bitmap.h:232:29: note:
      expanded from macro '_UCS_STATIC_BITMAP_UNARY_OP'
  232 |         ucs_typeof(_bitmap) _r_##_uid; \
      |                             ^
<scratch space>:54:1: note: expanded from here
   54 | _r_0
      | ^
core/ucp_context.c:2672:25: error: default initialization of an object of type
      'typeof (*tl_bitmap)' (aka 'const ucp_tl_bitmap_t') leaves the object uninitialized
      [-Werror,-Wdefault-const-init-var-unsafe]
 2672 |     ucp_tl_bitmap_t b = UCS_STATIC_BITMAP_AND(*tl_bitmap,
      |                         ^

This is cause due to Clang enabling default-const-init-var-unsafe by default,
and -Werror makes it treat as an warning. This is better fixed by upstream
developer so this commit mostly a RFC from upstream.

Signed-off-by: Brahmajit Das <listout@listout.xyz>