uct_mm_flush was defined inline in mm_iface.c and then declared inline in mm_iface.h.  GCC 5.1.1 generated warning/error
    mm_iface.h:102:21: error: inline function 'uct_mm_flush' declared but
    never defined [-Werror]
     inline ucs_status_t uct_mm_flush();

Removed the inline in both places.